name: JMeter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Java (JMeter dependency)
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jre-headless

      - name: Download and Extract Apache JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run Flipkart JMeter Test
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -n -t Flipkart.jmx -l results.jtl -e -o report
